compile:
	gcc -o iobound iobound.c
	gcc -o cpubound cpubound.c
	gcc -o part1 part1.c
	gcc -o part2 part2.c
	gcc -o part3 part3.c
	gcc -o part4 part4.c

clean:
	rm part1 part2 part3 part4 iobound cpubound
